config/routes.rb
Rails.application.routes.draw do
  root 'tags#new'

  resources :tags, only: [:create, :index]
  
  get 'signup'  => 'users#new' 
  resources :users
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  

end

app/models/animal.rb
class Animal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scan.rb
class Scan < ActiveRecord::Base
  validates :data, presence: true
  validates :number, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :data, presence: true
  validates :number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
	
  def require_user
    redirect_to '/login' unless current_user
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    @user = User.find_by_email(params[:session] [:email])
    if @user && @user.authenticate(params[:session] [:password])
      session[:user_id]=@user.id
      redirect_to '/'
    else
      redirect_to 'login'
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :require_user, only: [:index, :show]
  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to :root, notice: "Saved tag successfully!"
    else
      redirect_to :root, alert: "Unable to save tag: #{@tag.errors}"
    end
  end

  def index
    @tags = Tag.all
  end

  private
  def tag_params
    params.require(:tag).permit(:data, :number)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id]=@user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end
  
  private
  def user_params  
  	params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <div class="container">
      <div class="row">
        <%= link_to root_path do %>
          <img src="https://s3-us-west-2.amazonaws.com/velocitylaboratories/VelocityLogo.png">
        <% end %>

        <div class="nav pull-right">
          <ul class="nav nav-pills">
            <li class="active">
              <%= link_to "Home", :root %>
            </li>
            <li>
              <%= link_to "All Tags", tags_path %>
            </li>
            <% if current_user %> 
              <li><%= current_user.email %></li> 
              <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
            <% else %> 
              <li><%= link_to "Login", 'login' %></a></li> 
              <li><%= link_to "Signup", 'signup' %></a></li> 
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<%= yield %>

</body>
</html>

app/views/scans/new.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <h1>Scan Inventory Tag</h1>
    </div>
    <div id="video-form">
      <video id="video" width="320" height="200" autoplay></video>
      <section>
        <button id="btnTestPhoto">Generate test photo</button>
        <button id="btnStart">
          Start video
        </button>
        <button id="btnPhoto">
          Take a photo
        </button>
      </section>
      <canvas id="canvas" width="320" height="240"></canvas>
      <div class="row">
        <canvas id="hexnum" width="320" height="100"></canvas>
      </div>
      <%= form_for @scan, url: { action: "create" } do |f| %>
        <%= f.text_field :data, placeholder: "Data" %>
        <%= f.text_field :number, placeholder: "Number" %>
        <%= f.submit "Update Inventory" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tags/_tag.html.erb
<div class="tag">
  <strong><%= tag.data %></strong>
  (<%= tag.number %>)
</div>

app/views/tags/index.html.erb
<h2>All Scans</h2>
<hr/>
<% @tags.each do |tag| %>
  <%= render tag %>
<% end %>

app/views/tags/new.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <h1>Scan Inventory Tag</h1>
    </div>
    <div id="video-form">
      <video id="video" width="320" height="200" autoplay></video>
      <section>
        <button id="btnTestPhoto">Generate test photo</button>
        <button id="btnStart">
          Start video
        </button>
        <button id="btnPhoto">
          Take a photo
        </button>
      </section>
      <canvas id="canvas" width="320" height="240"></canvas>
      <div class="row">
        <canvas id="hexnum" width="320" height="100"></canvas>
      </div>
      <%= form_for @tag, url: { action: "create" } do |f| %>
        <%= f.text_field :data, placeholder: "Data" %>
        <%= f.text_field :number, placeholder: "Number" %>
        <%= f.submit "Update Inventory" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tags/show.html.erb
<h1>Tags#show</h1>

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

    <h1>Sign up</h1>

    <%= form_for(@user) do |f| %>
      <%= f.text_field :first_name, :placeholder => "First name" %>
      <%= f.text_field :last_name, :placeholder => "Last name" %>
      <%= f.email_field :email, :placeholder => "Email" %>
      <%= f.password_field :password, :placeholder => "Password" %>
      <%= f.submit "Create an account", class: "btn-submit" %>
    <% end %>

  
    </div>
  </div>
</div>